### ISSUE TITLE
Point to Acton instead of copying code here

### ISSUE THREAD

**Issue by chengsoonong** [ADACS-Australia/SS18A-JBanfield#1]
Instead of extern/acton, we should provide instructions on how to install acton and use the venv installed version from pypi, instead of using a copy of the acton code in this repo.

https://pypi.org/project/acton/

**Comment by macrocosme** [comment]
We do not use the code in `extern/acton` per se. We have packaged it there so that we can copy `extern/acton/proto` to the pip install location as it is not included when installing with pip.
