### ISSUE TITLE
First-time login takes a very long time

### ISSUE THREAD

**Issue by MatthewJA** [ADACS-Australia/SS18A-JBanfield#12]
I think it's running a classifier based on the warnings coming out in the terminal. Maybe this could be communicated to the user.

**Comment by macrocosme** [comment]
Indeed, if there is no survey already generated when going to /classify/, a predictor and a recommendation are created. I agree that letting the user know in some kind of async manner would be nice. We haven't had time to implement this.

**Comment by shiblisaleheen** [comment]
The survey generation if no survey present has been turned of, instead it will show a message 'No Survey Available'
