### ISSUE TITLE
Swap order of stretches

### ISSUE THREAD

**Issue by MatthewJA** [ADACS-Australia/SS18A-JBanfield#14]
If you change the stretching to

```python
AsinhStretch(0.01) + MinMaxInterval()
```

then the minmax will be applied first and it'll be much easier to see. Screenshot follows!

<img width="739" alt="screen shot 2018-06-06 at 2 09 00 pm" src="https://user-images.githubusercontent.com/2681312/41016528-3cbe0118-6993-11e8-9dcb-e35c1ff5405e.png">
<img width="740" alt="screen shot 2018-06-06 at 2 09 05 pm" src="https://user-images.githubusercontent.com/2681312/41016529-3d1784e0-6993-11e8-85bb-58c39747a15f.png">

**Comment by macrocosme** [comment]
I've changed it locally. I'll push the code with the next PR. FYI @shiblisaleheen
